job('First maven project via DSL') {
    description("First maven project generated by DSL  on ${new Date()}")
    scm {
        git("https://github.com/oscarvr13/schiller-americas-service.git", develop)
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean verify')
    }
    publishers {
        archiveArtifacts '**/*.jar'
    }
}

